import manifest from "@/public/model/book.pages.json";

export const MODEL_PATH = "/model/book.gltf";

/**
 * The model ships one continuous take in which every spine bone rotates in
 * turn. `STOPS` are the settled poses between those rotations, so scrubbing
 * from `STOPS[n]` to `STOPS[n + 1]` turns exactly one page -- rather than
 * playing the clip straight through and flipping the whole book at once.
 *
 * Regenerated by `npm run model:convert`.
 */
export const STOPS: readonly number[] = manifest.stops;

export const CLIP_NAME = manifest.clip;

/** Seconds one page turn should take, whatever rate it was authored at. */
export const TURN_SECONDS = 1.15;

/** Number of printed spreads between the covers. */
export const SPREAD_COUNT = manifest.spreadCount;

/** First stop is the closed book, last is the keepsake page at the end. */
export const FIRST_STOP = 0;
export const LAST_STOP = STOPS.length - 1;

export const clampStop = (stop: number) => Math.min(Math.max(stop, FIRST_STOP), LAST_STOP);

/** Seconds per page when flipping through several pages to reach one. */
export const FLIP_THROUGH_SECONDS = 0.75;

const AVERAGE_TURN = (STOPS[LAST_STOP] - STOPS[FIRST_STOP]) / LAST_STOP;

/**
 * Clip seconds to advance per real second when travelling from `fromTime`
 * to `toStop`. The speed is set per page, not per trip, so a jump across
 * several pages visibly folds each one in turn instead of blurring past.
 */
export function turnRate(fromTime: number, toStop: number) {
  const pages = Math.abs(STOPS[clampStop(toStop)] - fromTime) / AVERAGE_TURN;
  return AVERAGE_TURN / (pages > 1.5 ? FLIP_THROUGH_SECONDS : TURN_SECONDS);
}

export type StopLabel =
  | { kind: "cover"; title: string }
  | { kind: "spread"; title: string; spread: number }
  | { kind: "end"; title: string };

/**
 * What the reader is looking at once a stop has settled. Verified against
 * the rendered clip: stop 0 is the shut cover, stops 1-6 are the printed
 * spreads, and the final stop lands on the keepsake page.
 */
export function labelAt(stop: number): StopLabel {
  if (stop <= FIRST_STOP) return { kind: "cover", title: "Cover" };
  if (stop >= LAST_STOP) return { kind: "end", title: "The end" };
  return { kind: "spread", title: `Spread ${stop}`, spread: stop };
}
