import manifest from "@/public/model/book.pages.json";

export const MODEL_PATH = "/model/book.gltf";

export const CLIP_NAME = manifest.clip;

/**
 * Clip times where the book comes to rest, as authored. The model ships one
 * continuous take in which every spine bone rotates in turn, so scrubbing
 * from one of these to the next turns exactly one page -- rather than
 * playing the clip straight through and flipping the whole book at once.
 *
 * Regenerated by `npm run model:convert`.
 */
export const CLIP_STOPS: readonly number[] = manifest.stops;

const CLIP_END = CLIP_STOPS[CLIP_STOPS.length - 1];

/** Clip seconds that one authored page turn spans, on average. */
const AVERAGE_TURN = (CLIP_END - CLIP_STOPS[0]) / (CLIP_STOPS.length - 1);

/**
 * Every place the reader can stop, on one timeline. The clip ends on the
 * keepsake pocket; turning the book over to show its back cover has no
 * authored animation, so it is added as one more turn past the end of the
 * clip (see `poseAt`).
 */
export const STOPS: readonly number[] = [...CLIP_STOPS, CLIP_END + AVERAGE_TURN];

/** Seconds one page turn should take, whatever rate it was authored at. */
export const TURN_SECONDS = 1.15;

/** Number of printed spreads between the covers. */
export const SPREAD_COUNT = manifest.spreadCount;

export const FIRST_STOP = 0;
export const LAST_STOP = STOPS.length - 1;

/** The keepsake page, with the white card flipped open over its pocket. */
export const POCKET_STOP = LAST_STOP - 1;

/** The book turned over, showing its back cover. */
export const BACK_STOP = LAST_STOP;

export const clampStop = (stop: number) => Math.min(Math.max(stop, FIRST_STOP), LAST_STOP);

/** Seconds per page when flipping through several pages to reach one. */
export const FLIP_THROUGH_SECONDS = 0.75;

/**
 * Timeline seconds to advance per real second when travelling from
 * `fromTime` to `toStop`. The speed is set per page, not per trip, so a jump
 * across several pages visibly folds each one in turn instead of blurring past.
 */
export function turnRate(fromTime: number, toStop: number) {
  return turnRateTo(fromTime, STOPS[clampStop(toStop)]);
}

/**
 * As `turnRate`, but given the destination in timeline seconds. A book with
 * its own stop list (a custom book, which has no keepsake pocket) indexes
 * stops differently, so it works in times rather than stop numbers.
 */
export function turnRateTo(fromTime: number, toTime: number) {
  const pages = Math.abs(toTime - fromTime) / AVERAGE_TURN;
  return AVERAGE_TURN / (pages > 1.5 ? FLIP_THROUGH_SECONDS : TURN_SECONDS);
}

const smoothstep = (t: number) => t * t * (3 - 2 * t);

/**
 * Splits a timeline position into the clip time to pose the rig at, and how
 * far the book has been turned over (0 face up, 1 face down). Past the end of
 * the clip the pocket card closes again as the book turns, so it ends up
 * tucked away instead of hanging off the far side.
 */
export function poseAt(time: number) {
  if (time <= CLIP_END) return { clip: Math.max(time, 0), flip: 0 };

  const progress = Math.min((time - CLIP_END) / AVERAGE_TURN, 1);
  const cardShut = CLIP_STOPS[CLIP_STOPS.length - 2];
  return {
    clip: CLIP_END - (CLIP_END - cardShut) * smoothstep(Math.min(progress / 0.6, 1)),
    flip: smoothstep(progress),
  };
}

export type StopLabel =
  | { kind: "cover"; title: string }
  | { kind: "spread"; title: string; spread: number }
  | { kind: "pocket"; title: string }
  | { kind: "back"; title: string };

/**
 * What the reader is looking at once a stop has settled. Verified against
 * the rendered clip: stop 0 is the shut cover, stops 1-6 are the printed
 * spreads, then the keepsake pocket, then the book turned over.
 */
export function labelAt(stop: number): StopLabel {
  if (stop <= FIRST_STOP) return { kind: "cover", title: "Cover" };
  if (stop >= BACK_STOP) return { kind: "back", title: "Back cover" };
  if (stop === POCKET_STOP) return { kind: "pocket", title: "Your pocket" };
  return { kind: "spread", title: `Spread ${stop}`, spread: stop };
}
